[supervisord]
nodaemon=true


[program:websockify]
command=/usr/local/bin/websockify --web /opt/novnc 8080 localhost:5901
autostart=true
autorestart=true


[program:xfce]
command=/bin/bash -c "DISPLAY=:1 startxfce4"
autostart=true
autorestart=true
