[supervisord]
nodaemon=true


[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5901 --listen 8080
autostart=true
autorestart=true


[program:xfce]
command=/bin/bash -c "DISPLAY=:1 startxfce4"
autostart=true
autorestart=true
